version: '3'

networks:
  backend:
    external: true

services:
  csctracker:
    container_name: csctracker-schedule
    hostname: csctracker_schedule
    image: krlsedu/csctracker-schedule
    restart: always
    networks:
      - backend
    ports:
      - "5050:5000"
